language: python
python:
    - "2.7"
    - "3.6"
install:
    - python setup.py install
script:
    - python setup.py test
    - python ./pidlock.py --version
    - python ./pidlock.py --name test --command pwd --lockdir ~/.pidlock --verbose
