language: python
python:
    - "2.7"
    - "3.6"
install:
    - python setup.py install
script:
    - python ./pidlock.py --version
    - python ./pidlock.py --name test --command pwd --lockdir ~/.pidlock --verbose
    - python ./pidlock.py --name test --command pwd --lockdir ~/.pidlock --verbose -w 1 -m .05
    - python ./pidlock.py -n test -c pwd -l ~/.pidlock -v -w 1 -m .05
    - python ./pidlock.py -n test -c "sleep 10" -v &
    - python ./pidlock.py -n test -c "pwd" -v -w 3; [ $? -eq 1 ] || false
    - python ./pidlock.py -n test -c "pwd" -v -w 7 -m .5
